export const D1E1056article = () => (
  <div>
       <p >Guards or protective devices designed to protect against risks arising from moving parts shall be selected on the basis of the type of risk. The following guidelines shall be used to help to make the choice.</p>
            <p className="oj-ti-grseq-1" id="d1e1067-44-1">1.3.8.1.&nbsp;&nbsp;&nbsp;<span className="oj-expanded">Moving transmission parts</span>
            </p>
            <p >Guards designed to protect persons against the hazards generated by moving transmission parts shall be:</p>
            <table width="100%" border="0" cellSpacing="0" cellPadding="0">
               <colgroup><col width="4%"/>
               <col width="96%"/>
               </colgroup><tbody>
                  <tr>
                     <td valign="top">
                        <p >(a)</p>
                     </td>
                     <td valign="top">
                        <p >either fixed guards as referred to in section 1.4.2.1; or</p>
                     </td>
                  </tr>
               </tbody>
            </table>
            <table width="100%" border="0" cellSpacing="0" cellPadding="0">
               <colgroup><col width="4%"/>
               <col width="96%"/>
               </colgroup><tbody>
                  <tr>
                     <td valign="top">
                        <p >(b)</p>
                     </td>
                     <td valign="top">
                        <p >interlocking movable guards as referred to in section 1.4.2.2.</p>
                     </td>
                  </tr>
               </tbody>
            </table>
            <p >Interlocking movable guards shall be used where frequent access is envisaged.</p>
            <p className="oj-ti-grseq-1" id="d1e1093-44-1">1.3.8.2.&nbsp;&nbsp;&nbsp;<span className="oj-expanded">Moving parts involved in the process</span>
            </p>
            <p >Guards or protective devices designed to protect persons against the hazards generated by moving parts involved in the process shall be:</p>
            <table width="100%" border="0" cellSpacing="0" cellPadding="0">
               <colgroup><col width="4%"/>
               <col width="96%"/>
               </colgroup><tbody>
                  <tr>
                     <td valign="top">
                        <p >(a)</p>
                     </td>
                     <td valign="top">
                        <p >either fixed guards as referred to in section 1.4.2.1; or</p>
                     </td>
                  </tr>
               </tbody>
            </table>
            <table width="100%" border="0" cellSpacing="0" cellPadding="0">
               <colgroup><col width="4%"/>
               <col width="96%"/>
               </colgroup><tbody>
                  <tr>
                     <td valign="top">
                        <p >(b)</p>
                     </td>
                     <td valign="top">
                        <p >interlocking movable guards as referred to in section 1.4.2.2; or</p>
                     </td>
                  </tr>
               </tbody>
            </table>
            <table width="100%" border="0" cellSpacing="0" cellPadding="0">
               <colgroup><col width="4%"/>
               <col width="96%"/>
               </colgroup><tbody>
                  <tr>
                     <td valign="top">
                        <p >(c)</p>
                     </td>
                     <td valign="top">
                        <p >protective devices as referred to in section 1.4.3; or</p>
                     </td>
                  </tr>
               </tbody>
            </table>
            <table width="100%" border="0" cellSpacing="0" cellPadding="0">
               <colgroup><col width="4%"/>
               <col width="96%"/>
               </colgroup><tbody>
                  <tr>
                     <td valign="top">
                        <p >(d)</p>
                     </td>
                     <td valign="top">
                        <p >a combination of the above.</p>
                     </td>
                  </tr>
               </tbody>
            </table>
            <p >However, when certain moving parts directly involved in the process cannot be made completely inaccessible during operation owing to operations requiring operator intervention, such parts shall be fitted with:</p>
            <table width="100%" border="0" cellSpacing="0" cellPadding="0">
               <colgroup><col width="4%"/>
               <col width="96%"/>
               </colgroup><tbody>
                  <tr>
                     <td valign="top">
                        <p >(a)</p>
                     </td>
                     <td valign="top">
                        <p >fixed guards or interlocking movable guards preventing access to those sections of the parts that are not used in the work; and</p>
                     </td>
                  </tr>
               </tbody>
            </table>
            <table width="100%" border="0" cellSpacing="0" cellPadding="0">
               <colgroup><col width="4%"/>
               <col width="96%"/>
               </colgroup><tbody>
                  <tr>
                     <td valign="top">
                        <p >(b)</p>
                     </td>
                     <td valign="top">
                        <p >adjustable guards as referred to in section 1.4.2.3 restricting access to those sections of the moving parts where access is necessary.</p>
                     </td>
                  </tr>
               </tbody>
            </table>
  </div>
);

export const D1E1056history = () => <div>
    -
</div>;
