import { Typography } from '@mui/material';

export const D1E1164article = () => (
  <div>
    <Typography variant="subtitle1">1.4.1. General requirements</Typography>

    <p>Guards and protective devices shall:</p>
    <table width="100%" border="0" cellSpacing="0" cellPadding="0">
      <colgroup>
        <col width="4%" />
        <col width="96%" />
      </colgroup>
      <tbody>
        <tr>
          <td valign="top">
            <p>(a)</p>
          </td>
          <td valign="top">
            <p>be of robust construction;</p>
          </td>
        </tr>
      </tbody>
    </table>
    <table width="100%" border="0" cellSpacing="0" cellPadding="0">
      <colgroup>
        <col width="4%" />
        <col width="96%" />
      </colgroup>
      <tbody>
        <tr>
          <td valign="top">
            <p>(b)</p>
          </td>
          <td valign="top">
            <p>be securely held in place;</p>
          </td>
        </tr>
      </tbody>
    </table>
    <table width="100%" border="0" cellSpacing="0" cellPadding="0">
      <colgroup>
        <col width="4%" />
        <col width="96%" />
      </colgroup>
      <tbody>
        <tr>
          <td valign="top">
            <p>(c)</p>
          </td>
          <td valign="top">
            <p>not give rise to any additional hazard;</p>
          </td>
        </tr>
      </tbody>
    </table>
    <table width="100%" border="0" cellSpacing="0" cellPadding="0">
      <colgroup>
        <col width="4%" />
        <col width="96%" />
      </colgroup>
      <tbody>
        <tr>
          <td valign="top">
            <p>(d)</p>
          </td>
          <td valign="top">
            <p>not be easy to by-pass or render non-operational;</p>
          </td>
        </tr>
      </tbody>
    </table>
    <table width="100%" border="0" cellSpacing="0" cellPadding="0">
      <colgroup>
        <col width="4%" />
        <col width="96%" />
      </colgroup>
      <tbody>
        <tr>
          <td valign="top">
            <p>(e)</p>
          </td>
          <td valign="top">
            <p>be located at an adequate distance from the danger zone;</p>
          </td>
        </tr>
      </tbody>
    </table>
    <table width="100%" border="0" cellSpacing="0" cellPadding="0">
      <colgroup>
        <col width="4%" />
        <col width="96%" />
      </colgroup>
      <tbody>
        <tr>
          <td valign="top">
            <p>(f)</p>
          </td>
          <td valign="top">
            <p>cause minimum obstruction to the view of the production process, and;</p>
          </td>
        </tr>
      </tbody>
    </table>
    <table width="100%" border="0" cellSpacing="0" cellPadding="0">
      <colgroup>
        <col width="4%" />
        <col width="96%" />
      </colgroup>
      <tbody>
        <tr>
          <td valign="top">
            <p>(g)</p>
          </td>
          <td valign="top">
            <p>
              enable essential work to be carried out on the installation and/or replacement of tools and for
              maintenance purposes by restricting access exclusively to the area where the work has to be done, if
              possible without the guard having to be removed or the protective device having to be disabled.
            </p>
          </td>
        </tr>
      </tbody>
    </table>
    <p>
      In addition, guards shall, where possible, protect against the ejection or falling of materials or objects and
      against emissions generated by the machinery or related product.
    </p>
    {/* <p className="oj-ti-grseq-1" id="d1e1220-44-1"> </p> */}
   
  </div>
);
