export const D1E492article = () => (
  <div>
   <p  id="d1e501-44-1">1.2.1. &nbsp;<span className="oj-italic">Safety and reliability of control systems</span>
            </p>
            <p >Control systems shall be designed and constructed in such a way as to prevent hazardous situations from arising.</p>
            <p >Control systems shall be designed and constructed in such a way that:</p>
            <table width="100%" border="0" cellSpacing="0" cellPadding="0">
               <colgroup><col width="4%"/>
               <col width="96%"/>
               </colgroup><tbody>
                  <tr>
                     <td valign="top">
                        <p >(a)</p>
                     </td>
                     <td valign="top">
                        <p >they can withstand, where appropriate to the circumstances and the risks, the intended operating stresses and intended and unintended external influences, including reasonably foreseeable malicious attempts from third parties leading to a hazardous situation;</p>
                     </td>
                  </tr>
               </tbody>
            </table>
            <table width="100%" border="0" cellSpacing="0" cellPadding="0">
               <colgroup><col width="4%"/>
               <col width="96%"/>
               </colgroup><tbody>
                  <tr>
                     <td valign="top">
                        <p >(b)</p>
                     </td>
                     <td valign="top">
                        <p >a fault in the hardware or the logic of the control system shall not lead to hazardous situations;</p>
                     </td>
                  </tr>
               </tbody>
            </table>
            <table width="100%" border="0" cellSpacing="0" cellPadding="0">
               <colgroup><col width="4%"/>
               <col width="96%"/>
               </colgroup><tbody>
                  <tr>
                     <td valign="top">
                        <p >(c)</p>
                     </td>
                     <td valign="top">
                        <p >errors in the control system logic shall not lead to hazardous situations;</p>
                     </td>
                  </tr>
               </tbody>
            </table>
            <table width="100%" border="0" cellSpacing="0" cellPadding="0">
               <colgroup><col width="4%"/>
               <col width="96%"/>
               </colgroup><tbody>
                  <tr>
                     <td valign="top">
                        <p >(d)</p>
                     </td>
                     <td valign="top">
                        <p >the limits of the safety functions are to be established as part of the risk assessment performed by the manufacturer and no modifications are allowed to the settings or rules generated by the machinery or related product or by operators, including during the machinery or related product learning phase, where such modifications could lead to hazardous situations;</p>
                     </td>
                  </tr>
               </tbody>
            </table>
            <table width="100%" border="0" cellSpacing="0" cellPadding="0">
               <colgroup><col width="4%"/>
               <col width="96%"/>
               </colgroup><tbody>
                  <tr>
                     <td valign="top">
                        <p >(e)</p>
                     </td>
                     <td valign="top">
                        <p >reasonably foreseeable human errors during operation shall not lead to hazardous situations;</p>
                     </td>
                  </tr>
               </tbody>
            </table>
            <table width="100%" border="0" cellSpacing="0" cellPadding="0">
               <colgroup><col width="4%"/>
               <col width="96%"/>
               </colgroup><tbody>
                  <tr>
                     <td valign="top">
                        <p >(f)</p>
                     </td>
                     <td valign="top">
                        <p >the tracing log of the data generated in relation to an intervention and of the versions of safety software uploaded after the machinery or related product has been placed on the market or put into service is enabled for five years after such upload, exclusively to demonstrate the conformity of the machinery or related product with this Annex further to a reasoned request from a competent national authority.</p>
                     </td>
                  </tr>
               </tbody>
            </table>
            <p >Control systems of machinery or related products with fully or partially self-evolving behaviour or logic that are designed to operate with varying levels of autonomy shall be designed and constructed in such a way that:</p>
            <table width="100%" border="0" cellSpacing="0" cellPadding="0">
               <colgroup><col width="4%"/>
               <col width="96%"/>
               </colgroup><tbody>
                  <tr>
                     <td valign="top">
                        <p >(a)</p>
                     </td>
                     <td valign="top">
                        <p >they shall not cause the machinery or related product to perform actions beyond its defined task and movement space;</p>
                     </td>
                  </tr>
               </tbody>
            </table>
            <table width="100%" border="0" cellSpacing="0" cellPadding="0">
               <colgroup><col width="4%"/>
               <col width="96%"/>
               </colgroup><tbody>
                  <tr>
                     <td valign="top">
                        <p >(b)</p>
                     </td>
                     <td valign="top">
                        <p >recording of data on the safety related decision-making process for software based safety systems ensuring safety function including safety components, after the machinery or related product has been placed on the market or put into service, is enabled and that such data is retained for one year after its collection, exclusively to demonstrate the conformity of the machinery or related product with this Annex further to a reasoned request from a competent national authority;</p>
                     </td>
                  </tr>
               </tbody>
            </table>
            <table width="100%" border="0" cellSpacing="0" cellPadding="0">
               <colgroup><col width="4%"/>
               <col width="96%"/>
               </colgroup><tbody>
                  <tr>
                     <td valign="top">
                        <p >(c)</p>
                     </td>
                     <td valign="top">
                        <p >it shall be possible at all times to correct the machinery or related product in order to maintain its inherent safety.</p>
                     </td>
                  </tr>
               </tbody>
            </table>
            <p >Particular attention shall be given to the following points:</p>
            <table width="100%" border="0" cellSpacing="0" cellPadding="0">
               <colgroup><col width="4%"/>
               <col width="96%"/>
               </colgroup><tbody>
                  <tr>
                     <td valign="top">
                        <p >(a)</p>
                     </td>
                     <td valign="top">
                        <p >the machinery or related product shall not start unexpectedly;</p>
                     </td>
                  </tr>
               </tbody>
            </table>
            <table width="100%" border="0" cellSpacing="0" cellPadding="0">
               <colgroup><col width="4%"/>
               <col width="96%"/>
               </colgroup><tbody>
                  <tr>
                     <td valign="top">
                        <p >(b)</p>
                     </td>
                     <td valign="top">
                        <p >the parameters of the machinery or related product shall not change in an uncontrolled way, where such change could lead to hazardous situations;</p>
                     </td>
                  </tr>
               </tbody>
            </table>
            <table width="100%" border="0" cellSpacing="0" cellPadding="0">
               <colgroup><col width="4%"/>
               <col width="96%"/>
               </colgroup><tbody>
                  <tr>
                     <td valign="top">
                        <p >(c)</p>
                     </td>
                     <td valign="top">
                        <p >modifications to the settings or rules, generated by the machinery or related product or by operators, including during the machinery or related product learning phase, shall be prevented, where such modifications could lead to hazardous situations;</p>
                     </td>
                  </tr>
               </tbody>
            </table>
            <table width="100%" border="0" cellSpacing="0" cellPadding="0">
               <colgroup><col width="4%"/>
               <col width="96%"/>
               </colgroup><tbody>
                  <tr>
                     <td valign="top">
                        <p >(d)</p>
                     </td>
                     <td valign="top">
                        <p >the machinery or related product shall not be prevented from stopping if the stop command has already been given;</p>
                     </td>
                  </tr>
               </tbody>
            </table>
            <table width="100%" border="0" cellSpacing="0" cellPadding="0">
               <colgroup><col width="4%"/>
               <col width="96%"/>
               </colgroup><tbody>
                  <tr>
                     <td valign="top">
                        <p >(e)</p>
                     </td>
                     <td valign="top">
                        <p >no moving part of the machinery or related product or piece held by the machinery or related product shall fall or be ejected;</p>
                     </td>
                  </tr>
               </tbody>
            </table>
            <table width="100%" border="0" cellSpacing="0" cellPadding="0">
               <colgroup><col width="4%"/>
               <col width="96%"/>
               </colgroup><tbody>
                  <tr>
                     <td valign="top">
                        <p >(f)</p>
                     </td>
                     <td valign="top">
                        <p >automatic or manual stopping of the moving parts, whatever they may be, shall be unimpeded;</p>
                     </td>
                  </tr>
               </tbody>
            </table>
            <table width="100%" border="0" cellSpacing="0" cellPadding="0">
               <colgroup><col width="4%"/>
               <col width="96%"/>
               </colgroup><tbody>
                  <tr>
                     <td valign="top">
                        <p >(g)</p>
                     </td>
                     <td valign="top">
                        <p >the protective devices shall remain fully effective or give a stop command;</p>
                     </td>
                  </tr>
               </tbody>
            </table>
            <table width="100%" border="0" cellSpacing="0" cellPadding="0">
               <colgroup><col width="4%"/>
               <col width="96%"/>
               </colgroup><tbody>
                  <tr>
                     <td valign="top">
                        <p >(h)</p>
                     </td>
                     <td valign="top">
                        <p >the safety-related parts of the control system shall apply in a coherent way to the whole of an assembly of machinery or related products or partly completed machinery, or a combination thereof.</p>
                     </td>
                  </tr>
               </tbody>
            </table>
            <p >For wireless control, a failure of the communication or connection or a faulty connection shall not lead to a hazardous situation.</p>
  </div>
);

export const D1E492history = () => (
  <div>
    <table>
        <thead>
          <tr>
            {/* <th width="35%">2006/42/EC</th> */}
            <th width="55%">2023/1230/EC</th>
            <th>Remarks</th>
          </tr>
        </thead>
<tbody>
  <tr>
    
    <td>(a) they can withstand, <font color="blue"> where appropriate to the circumstances and the risks,</font> the intended operating stresses and intended and unintended external influences, <font color="blue"> including reasonably foreseeable malicious attempts from third parties leading to a hazardous situation </font></td>
    <td  valign="top">(a) 위험한 상황을 초래할 수 있는 합리적으로 예측 가능한 제3자의 악의적인 시도를 포함<br/></td>
  </tr>
  <tr>
    <td>(d) the limits of the safety functions are to be established as part of the risk assessment performed by the manufacturer and no modifications are allowed to the settings or rules generated by the machinery or related product or by operators, including during the machinery or related product learning phase, where such modifications could lead to hazardous situations;</td>
    <td  valign="top">(d) 안전 기능의 한계는 제조업체가 수행하는 위험 평가의 일부로 설정되어야 하며, 기계 또는 관련 제품에 의해 생성된 설정 또는 규칙을 기계 또는 관련 제품 학습 단계를 포함하여 작업자가 위험한 상황을 초래할 수 있는 수정을 할 수 없어야 한다</td>
  </tr>
  <tr>
    <td >(f) the tracing log of the data generated in relation to an intervention and of the versions of safety software uploaded after the machinery or related product has been placed on the market or put into service is enabled for five years after such upload, exclusively to demonstrate the conformity of the machinery or related product with this Annex further to a reasoned request from a competent national authority.</td>
    <td valign="top">(f) 개입과 관련하여 생성된 데이터 및 기계류 또는 관련 제품이 시장에 출시되거나 서비스에 투입된 후 업로드된 안전 소프트웨어 버전의 추적 로그는 해당 업로드 후 5년 동안, 관할 국가 기관의 합리적인 요청에 따라 기계류 또는 관련 제품이 이 부속서를 준수함을 입증하기 위한 용도로만 사용할 수 있다.</td>
  </tr>
  <tr>
    <td>Control systems of machinery or related products with fully or partially self-evolving behaviour or logic that are designed to operate with varying levels of autonomy shall be designed and constructed in such a way that:</td>
    <td valign="top">다양한 수준의 자율성으로 작동하도록 설계된 전체 또는 부분적으로 스스로 진화하는 동작 또는 로직이 있는 기계 또는 관련 제품의 제어 시스템은 다음과 같은 방식으로 설계 및 구축되어야 한다:</td>
  </tr>
  <tr>
    <td>(a)    they shall not cause the machinery or related product to perform actions beyond its defined task and movement space;</td>
    <td valign="top">(a) 기계 또는 관련 제품이 정의된 작업 및 이동 공간을 벗어난 동작을 수행하지 않도록 해야 한다;</td>
  </tr>
  <tr>
    <td>(b)    recording of data on the safety related decision-making process for software based safety systems ensuring safety function including safety components, after the machinery or related product has been placed on the market or put into service, is enabled and that such data is retained for one year after its collection, exclusively to demonstrate the conformity of the machinery or related product with this Annex further to a reasoned request from a competent national authority;</td>
    <td valign="top">(b) 기계류 또는 관련 제품이 시장에 출시되거나 서비스에 투입된 후 안전 구성 요소를 포함한 안전 기능을 보장하는 소프트웨어 기반 안전 시스템에 대한 안전 관련 의사 결정 프로세스에 대한 데이터를 기록하고, 해당 데이터는 관할 국가 기관의 합리적인 요청에 따라 기계류 또는 관련 제품이 이 부속서를 준수함을 입증하기 위한 목적으로만 수집 후 1년간 보관할 수 있어야 한다;</td>
  </tr>
  <tr>
    <td>(c)    it shall be possible at all times to correct the machinery or related product in order to maintain its inherent safety.</td>
    <td valign="top">(c) 기계류 또는 관련 제품의 고유한 안전성을 유지하기 위해 기계류 또는 관련 제품을 수정하는 것이 항상 가능해야 한다.</td>
  </tr>
  <tr>
    <td>(c)    modifications to the settings or rules, generated by the machinery or related product or by operators, including during the machinery or related product learning phase, shall be prevented, where such modifications could lead to hazardous situations;</td>
    <td valign="top">(c) 기계 또는 관련 제품의 학습 또는 작업자가 생성한 설정 또는 규칙의 수정은 위험한 상황을 초래할 수 있는 경우 방지되어야 한다;<br/></td>
  </tr>
</tbody>
      </table>
  </div>
);
