export const NPD_DTR = [
  {
    name: "guardrail",
    label: "GuardRail",
    group: "access",
    market: "common",
    state: "green",
  },
  {
    name: "tieDownLifting",
    label: "Tie Down & Lifting",
    group: "access",
    market: "common",
    state: "green",
  },
  {
    name: "retrieval",
    label: "Retrieval",
    group: "access",
    market: "common",
    state: "green",
  },
  {
    name: "tankNcap",
    label: "Tank & Cap",
    group: "access",
    market: "common",
    state: "green",
  },
  {
    name: "articulateFrame",
    label: "Articulate Frame",
    group: "access",
    market: "common",
    state: "green",
  },
  {
    name: "ropsOpg",
    label: "ROPS/OPG/TOPS/OPS",
    group: "operatorStation",
    market: "EU",
    state: "green",
  },
  {
    name: "visibility",
    label: "Visibility",
    group: "operatorStation",
    market: "common",
    state: "green",
  },
  {
    name: "fireProtection",
    label: "Fire Protection",
    group: "operatorStation",
    market: "common",
    state: "green",
  },
  {
    name: "minimumSpace",
    label: "Minimum Space",
    group: "operatorStation",
    market: "common",
    state: "green",
  },
  {
    name: "comport_Reach",
    label: "Comport & Reach Zone",
    group: "operatorStation",
    market: "common",
    state: "green",
  },
  {
    name: "seat",
    label: "Seat",
    group: "operatorStation",
    market: "common",
    state: "green",
  },
  {
    name: "controlSystem",
    label: "Control system",
    group: "operatorStation",
    market: "common",
    state: "green",
  },
  {
    name: "pipeHose",
    label: "Pipe Hose",
    group: "operatorStation",
    market: "common",
    state: "green",
  },
  {
    name: "instructionStorage",
    label: "Instruction Storage",
    group: "operatorStation",
    market: "common",
    state: "green",
  },
  {
    name: "hotParts",
    label: "Hot Parts",
    group: "structure",
    market: "common",
    state: "green",
  },
  {
    name: "guard",
    label: "Guard",
    group: "structure",
    market: "common",
    state: "green",
  },
  {
    name: "tireNrim",
    label: "Tire and Rim",
    group: "structure",
    market: "common",
    state: "green",
  },
  {
    name: "controlPanel",
    label: "Control Panel",
    group: "electric",
    market: "common",
    state: "green",
  },
  {
    name: "degreeProtection ",
    label: "Degree of Protection ",
    group: "electric",
    market: "common",
    state: "green",
  },
  {
    name: "electricConnections",
    label: "Electric connections",
    group: "electric",
    market: "common",
    state: "green",
  },
  {
    name: "batteryNdisconnection",
    label: "Battery / Disconnection",
    group: "electric",
    market: "common",
    state: "green",
  },
  {
    name: "electricSocket",
    label: "Electric socket",
    group: "electric",
    market: "common",
    state: "green",
  },
  {
    name: "lightingDevice",
    label: "Lighting Device",
    group: "electric",
    market: "common",
    state: "green",
  },
  {
    name: "quickCouplerSystem",
    label: "Quick Coupler system",
    group: "electric",
    market: "common",
    state: "green",
  },
  {
    name: "travelAlarm",
    label: "Travel Alarm",
    group: "electric",
    market: "common",
    state: "green",
  },
  {
    name: "pressurizedEquipment",
    label: "Pressurized equipment",
    group: "hydraulics",
    market: "common",
    state: "green",
  },
  {
    name: "hydraulicLineHoses",
    label: "Hydraulic Line / Hoses",
    group: "hydraulics",
    market: "common",
    state: "green",
  },
  {
    name: "attachmentLowering",
    label: "Attachment Lowering",
    group: "hydraulics",
    market: "EU",
    state: "green",
  },
  {
    name: "dozerStability",
    label: "Dozer Stability",
    group: "hydraulics",
    market: "common",
    state: "green",
  },
  {
    name: "stage5",
    label: "Stage 5",
    group: "certification",
    market: "Korea",
    state: "green",
  },
  {
    name: "koTypeApproval",
    label: "형식승인",
    group: "certification",
    market: "Korea",
    state: "green",
  },
  {
    name: "stageV",
    label: "Stage V",
    group: "certification",
    market: "EU",
    state: "green",
  },
  {
    name: "certeCE",
    label: "CE Marking",
    group: "certification",
    market: "EU",
    state: "green",
  },
  {
    name: "roadHomologation",
    label: "Road Homologation",
    group: "certification",
    market: "EU",
    state: "green",
  },
  {
    name: "emc",
    label: "EMC",
    group: "certification",
    market: ["EU", "Russia", "northAmerica"],
    state: "green",
  },
  {
    name: "noiseEmission",
    label: "Noise Emission",
    group: "certification",
    market: ["EU", "China", "Korea", "Brazil"],
    state: "green",
  },
];

/* 

export const NPD_DTR = {
  stepPlatform: {
    group: "Access",
    label: "Step/Platform",
    state: "green",
    market: ["EU", "Korea", "NorthAmerica"],
  },
  handrail: {
    group: "Access",
    label: "Handrail",
    state: "green",
    market: ["EU", "Korea", "NorthAmerica"],
  },
  stepPlatform: {
    group: "Access",
    label: "Step/Platform",
    state: "green",
    market: ["EU", "Korea", "NorthAmerica"],
  },
  degreeProtection: {
    group: "Electric",
    label: "Degree of Protection",
    state: "green",
    market: ["EU", "Korea", "NorthAmerica"],
  },
  
  noiseEmission: {
    group: "MarketSpecific",
    label: "Noise Emission",
    state: "green",
    market: ["EU", "Korea", "China", "Brazil"],
  },
  
};

 */
