export const NPD_DTR = [
  {
    name: "guardrail",
    label: "Guardrail",
    group: "access",
    market: "EU",
    state: "green",
  },
  {
    name: "handrail",
    label: "Handrail",
    group: "access",
    market: "common",
    state: "green",
  },
  {
    name: "stepPlatform",
    label: "Step/Platform",
    group: "access",
    market: "common",
    state: "green",
  },
  {
    name: "opening",
    label: "Opening",
    group: "access",
    market: "common",
    state: "green",
  },
  {
    name: "tieDownLifting",
    label: "Tie Down & Lifting",
    group: "structure",
    market: "common",
    state: "green",
  },
  {
    name: "retrieval",
    label: "Retrieval",
    group: "structure",
    market: "common",
    state: "green",
  },
  {
    name: "tankNcap",
    label: "Tank & Cap",
    group: "structure",
    market: "common",
    state: "green",
  },
  {
    name: "articulateFrame",
    label: "Articulate Frame",
    group: "structure",
    market: "common",
    state: "green",
  },
  {
    name: "ropsOpg",
    label: "ROPS/OPG/TOPS/OPS",
    group: "operatorStation",
    market: "EU",
    state: "green",
  },
  {
    name: "visibility",
    label: "Visibility",
    group: "operatorStation",
    market: "common",
    state: "green",
  },
  {
    name: "fireProtection",
    label: "Fire Protection",
    group: "operatorStation",
    market: "common",
    state: "green",
  },
  {
    name: "minimumSpace",
    label: "Minimum Space",
    group: "operatorStation",
    market: "common",
    state: "green",
  },
  {
    name: "comport_Reach",
    label: "Comport & Reach Zone",
    group: "operatorStation",
    market: "common",
    state: "green",
  },
  {
    name: "seat",
    label: "Seat",
    group: "operatorStation",
    market: "common",
    state: "green",
  },
  {
    name: "controlSystem",
    label: "Control system",
    group: "operatorStation",
    market: "common",
    state: "green",
  },
  {
    name: "pipeHose",
    label: "Pipe Hose",
    group: "operatorStation",
    market: "common",
    state: "green",
  },
  {
    name: "instructionStorage",
    label: "Instruction Storage",
    group: "operatorStation",
    market: "common",
    state: "green",
  },
  {
    name: "hotParts",
    label: "Hot Parts",
    group: "powerTrain",
    market: "common",
    state: "green",
  },
  {
    name: "guard",
    label: "Guard",
    group: "powerTrain",
    market: "common",
    state: "green",
  },
  {
    name: "tireNrim",
    label: "Tire and Rim",
    group: "powerTrain",
    market: "common",
    state: "green",
  },
  {
    name: "controlPanel",
    label: "Control Panel",
    group: "electric",
    market: "common",
    state: "green",
  },
  {
    name: "degreeProtection ",
    label: "Degree of Protection ",
    group: "electric",
    market: "common",
    state: "green",
  },
  {
    name: "electricConnections",
    label: "Electric connections",
    group: "electric",
    market: "common",
    state: "green",
  },
  {
    name: "batteryNdisconnection",
    label: "Battery / Disconnection",
    group: "electric",
    market: "common",
    state: "green",
  },
  {
    name: "electricSocket",
    label: "Electric socket",
    group: "electric",
    market: "common",
    state: "green",
  },
  {
    name: "lightingDevice",
    label: "Lighting Device",
    group: "electric",
    market: "common",
    state: "green",
  },
  {
    name: "quickCouplerSystem",
    label: "Quick Coupler system",
    group: "electric",
    market: "common",
    state: "green",
  },
  {
    name: "travelAlarm",
    label: "Travel Alarm",
    group: "electric",
    market: ["EU", "Australia"],
    state: "green",
  },
  {
    name: "pressurizedEquipment",
    label: "Pressurized equipment",
    group: "hydraulics",
    market: "common",
    state: "green",
  },
  {
    name: "hydraulicLineHoses",
    label: "Hydraulic Line / Hoses",
    group: "hydraulics",
    market: "common",
    state: "green",
  },
  {
    name: "attachmentLowering",
    label: "Attachment Lowering",
    group: "hydraulics",
    market: "EU",
    state: "green",
  },
  {
    name: "dozerStability",
    label: "Dozer Stability",
    group: "hydraulics",
    market: "common",
    state: "green",
  },
  {
    name: "stage5",
    label: "Stage 5",
    group: "certification",
    market: "Korea",
    state: "green",
  },
  {
    name: "koTypeApproval",
    label: "형식승인",
    group: "certification",
    market: "Korea",
    state: "green",
  },
  {
    name: "stageV",
    label: "Stage V",
    group: "certification",
    market: "EU",
    state: "green",
  },
  {
    name: "certeCE",
    label: "CE Marking",
    group: "certification",
    market: "EU",
    state: "green",
  },
  {
    name: "roadHomologation",
    label: "Road Homologation",
    group: "certification",
    market: "EU",
    state: "green",
  },
  {
    name: "emc",
    label: "EMC",
    group: "certification",
    market: ["EU", "cutr", "northAmerica"],
    state: "green",
  },
  {
    name: "noiseEmission",
    label: "Noise Emission",
    group: "certification",
    market: ["EU", "China", "Korea", "Brazil"],
    state: "green",
  },
];

export const NPD_FDR = [
  {
    name: "guardrail",
    label: "Guardrail",
    group: "access",
    market: "EU",
    state: "green",
    description: "CarryOver",
  },
  {
    name: "handrail",
    label: "Handrail",
    group: "access",
    market: "common",
    state: "green",
    description: "CarryOver",
  },
  {
    name: "stepPlatform",
    label: "Step/Platform",
    group: "access",
    market: "common",
    state: "green",
    description: "CarryOver",
  },
  {
    name: "opening",
    label: "Opening",
    group: "access",
    market: "common",
    state: "green",
    description: "",
  },
  {
    name: "tieDownLifting",
    label: "Tie Down & Lifting",
    group: "structure",
    market: "common",
    state: "green",
    description: "CarryOver",
  },
  {
    name: "retrieval",
    label: "Retrieval",
    group: "structure",
    market: "common",
    state: "green",
    description: "CarryOver",
  },
  {
    name: "tankNcap",
    label: "Tank & Cap",
    group: "structure",
    market: "common",
    state: "green",
    description: "",
  },
  {
    name: "articulateFrame",
    label: "Articulate Frame",
    group: "structure",
    market: "common",
    state: "green",
    description: "",
  },
  {
    name: "ropsOpg",
    label: "ROPS/OPG/TOPS/OPS",
    group: "operatorStation",
    market: "EU",
    state: "green",
    description: "CarryOver",
  },
  {
    name: "visibility",
    label: "Visibility",
    group: "operatorStation",
    market: "common",
    state: "green",
    description: "CarryOver",
  },
  {
    name: "fireProtection",
    label: "Fire Protection",
    group: "operatorStation",
    market: "common",
    state: "green",
    description: "CarryOver",
  },
];

export const NPD_PVC = [ {
    name: "serviceBrake",
    label: "Service Brake",
    group: "brake",
    market: "common",
    state: "green",
  },
  {
    name: "secondaryBrake",
    label: "Secondary Brake",
    group: "brake",
    market: "common",
    state: "green",
  },
  {
    name: "parkingBrake",
    label: "Parking Brake",
    group: "brake",
    market: "common",
    state: "green",
  },
  {
    name: "swingBrake",
    label: "Swing Brake",
    group: "brake",
    market: "common",
    state: "green",
  },
  {
    name: "normalSteering",
    label: "Normal Steering",
    group: "steering",
    market: "common",
    state: "green",
  },
  {
    name: "emergencySteering",
    label: "Emergency Steering",
    group: "steering",
    market: "EU",
    state: "green",
  },
  {
    name: "ropsOpgTopsOps",
    label: "ROPS/OPG/TOPS/OPS",
    group: "protective",
    market: "EU",
    state: "green",
  },
  {
    name: "heatingSystem",
    label: "Heating System",
    group: "HVAC",
    market: "EU",
    state: "green",
  },
  {
    name: "ventilationSystem",
    label: "Ventilation System",
    group: "HVAC",
    market: "EU",
    state: "green",
  },
  {
    name: "defrostingSystem",
    label: "Defrosting System",
    group: "HVAC",
    market: "EU",
    state: "green",
  },
  {
    name: "pressurizationSystem",
    label: "Pressurization System",
    group: "HVAC",
    market: "EU",
    state: "green",
  },
  {
    name: "lowering controlDevice",
    label: "Lowering control device",
    group: "objectHandling",
    market: "EU",
    state: "green",
  },
  {
    name: "dozer controlDevice",
    label: "Dozer control device",
    group: "objectHandling",
    market: "EU",
    state: "green",
  },
  {
    name: "horn",
    label: "Horn",
    group: "electric",
    market: "common",
    state: "green",
  },
  {
    name: "visibility",
    label: "Visibility (AVM)",
    group: "electric",
    market: "EU, northAmerica",
    state: "green",
  },
  {
    name: "engineEmissionEU",
    label: "EU (Stage V)",
    group: "engineEmission",
    market: "EU",
    state: "green",
  },
  {
    name: "engineEmissionNA",
    label: "North America (Tier 4F)",
    group: "engineEmission",
    market: "northAmerica",
    state: "green",
  },
  {
    name: "engineEmissionKor",
    label: "Korea (Stage 5)",
    group: "engineEmission",
    market: "Korea",
    state: "green",
  },
  {
    name: "engineEmissionChina",
    label: "China (G4)",
    group: "engineEmission",
    market: "China",
    state: "green",
  },
  {
    name: "engineEmissionBra",
    label: "Brazil (T3)",
    group: "engineEmission",
    market: "Brazil",
    state: "green",
  },
  {
    name: "noise",
    label: "Noise",
    group: "noiseVibration",
    market: ["EU", "China", "Korea", "brazil"],
    state: "green",
  },
  {
    name: "wbvHbv",
    label: "WBV /HBV",
    group: "noiseVibration",
    market: "EU",
    state: "green",
  },
];
